name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        

      - name: Install Dependencies
        run: npm install
        
      - name: Build
        run: |
          npm run build
          yarn next export
          
      - name: Create tar file
        run: tar -cvf out.tar ./out
          
      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_IP_ADDRESS }} # Host of the EC2 instance
          username: ${{ secrets.EC2_USER_NAME }} # Username to login
          key: ${{ secrets.EC2_PEM }} # Key to connect to EC2 instance
          source: "out.tar"
          target: "/var/out"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP_ADDRESS }} # Host of the EC2 instance
          username: ${{ secrets.EC2_USER_NAME }} # Username to login
          key: ${{ secrets.EC2_PEM }} # Key to connect to EC2 instance
          script: |
            cd /var/out/
            tar -xvf out.tar
            rm out.tar
