name: Checkout and Build on EC2

on:
  push:
    branches:
      - main

jobs:
  checkout-and-build-on-EC2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.0.0
          cache: 'npm'
      - name: Install modules
        run: npm install
      - name: Build project
        run: npm run build
      - name: Deploy build outputs
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_IP_ADDRESS }}
          username: ${{ secrets.EC2_USER_NAME }}
          key: ${{ secrets.EC2_PEM }}
          port: 22
          source: '.next/*'
          strip_components: 1
          target: '/keewe-front/.next'
      - name: Deploy .git
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_IP_ADDRESS }}
          username: ${{ secrets.EC2_USER_NAME }}
          key: ${{ secrets.EC2_PEM }}
          port: 22
          source: '.git'
          strip_components: 1
          target: '/keewe-front'
