name: Checkout and Build on EC2

on:
  push:
    branches: 
      - main

jobs:
  checkout-and-build-on-EC2:
    runs-on: ubuntu-latest

    steps:
      - name: Build and deploy
        run: |
          echo "${{ secrets.EC2_PEM }}" > $HOME/key.pem
          chmod 400 $HOME/key.pem
          ssh -i $HOME/key.pem -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOSTS} "cd /home/ec2-user/keewe/keewe-front; sudo git pull origin main; sudo npm install; sudo npm run build; sudo npm start;"
        env:
          SSH_USER: ${{secrets.EC2_USER_NAME}}
          SSH_HOSTS: ${{secrets.EC2_IP_ADDRESS}}
