name: Checkout and Build on EC2

on:
  push:
    branches:
      - main

jobs:
  checkout-and-build-on-EC2:
    runs-on: ubuntu-latest

    steps:
      - name: Build and deploy
        run: |
          echo "$SSH_PEM" >> $HOME/key.pem
          chmod 400 $HOME/key.pem
          ssh -i $HOME/key.pem -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOSTS} '~/script.sh'
          cd /home/keewe
          git checkout main
          git pull
          npm install
          npm run build
          yarn next export
        env:
          SSH_USER: ${{secrets.EC2_USER_NAME}}
          SSH_HOSTS: ${{secrets.EC2_IP_ADDRESS}}
          SSH_PEM: ${{secrets.EC2_PEM}}
