name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Set up PEM key
        run: echo "${{ secrets.EC2_PEM_KEY }}" > ec2.pem
        env:
          SSH_PRIVATE_KEY: ec2.pem

      - name: Set correct permissions for PEM key
        run: chmod 400 ec2.pem
        
      - name: Build
        run: |
          npm run build
          yarn next export

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          args: |
            --src=./out/
            --remote=ubuntu@${{ secrets.EC2_IP_ADDRESS }}:/var/www/html/ 
